export const SUPPORTED_BILLERS = [
  'mtn',
  'airtel',
  'glo',
  '9mobile',
  'dstv',
  'gotv',
  'startimes',
  'spectranet',
  'smile-direct',
  'aba',
  'abuja',
  'benin',
  'eko',
  'enugu',
  'ibadan',
  'ikeja',
  'jos',
  'kano',
  'kaduna',
  'portharcourt',
  'yola',
];

export const SUPPORTED_ELECTRICITY_PROVIDERS = {
  abuja: 'aedc',
  aba: 'aba',
  benin: ['bedc', 'bendc'],
  eko: 'ekedc',
  enugu: 'eedc',
  ibadan: 'ibedc',
  ikeja: 'ikedc',
  jos: ['jed', 'jedc'],
  kaduna: 'kaedco',
  kano: 'kedcoo',
  portharcourt: 'phed',
  yola: 'yedc',
};

export const SUPPORTED_BILL_ITEMS = {
  'Mobile Recharge': ['MTN', 'Airtel', 'Globacom', 'Airtel T2'],
  'Airtime and Data': ['MTN', 'Airtel', 'Globacom'],
  'Airtel Data': ['Airtel Data'],
  'Cable TV': ['DSTV', 'GOTV', 'Startimes'],
  'Cable TV Bills': ['DSTV', 'GOTV', 'Startimes'],
};
